# Verifiable Source: Official PX4 Docs & Docker Hub Image Details
# This file orchestrates the multi-container environment for the AscentVTOL project,
# using the official pre-built PX4 simulation image.
version: '3.8'

services:
  # The PX4 development and simulation container using the official image
  px4-dev:
    image: px4io/px4-dev-simulation-jammy:latest
    container_name: ascent-px4
    privileged: true # Required for some simulation hardware access
    stdin_open: true # Keeps the container running
    tty: true
    network_mode: "host" # Simplifies networking for Gazebo, ROS, and QCS
    volumes:
      # Mount your local PX4 source code into the container
      - ./PX4-Autopilot:/home/user/PX4-Autopilot:rw
      # Mount X11 socket for GUI forwarding from the container to your host
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      # Pass host's DISPLAY variable and user ID for permissions
      - DISPLAY=${DISPLAY}
      - LOCAL_USER_ID=${UID}

  # The ROS 2 development container (still built locally)
  ros-dev:
    build:
      context: .
      dockerfile: ros.Dockerfile
    container_name: ascent-ros
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ./ros2_ws:/home/user/ros2_ws

  # The Micro XRCE-DDS Agent container (still built locally)
  xrce-dds-agent:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: ascent-xrce-agent
    network_mode: "host"

